### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by caharding** [ushahidi/tenfour-mobile#2]
- [ ] Owner can view payment plan [details](https://docs.google.com/document/d/1zc9bz2dRCD7tCiSiwO__MkCQoGXo4CnVO3x-U9WMty0/edit#)  
- [ ] Owner can add and edit credit card payment [details](https://docs.google.com/document/d/1zc9bz2dRCD7tCiSiwO__MkCQoGXo4CnVO3x-U9WMty0/edit#)
- [ ]  Owner can purchase a monthly SMS plan [Reference](https://github.com/ushahidi/RollCall/issues/23) 
- [ ]  Owner can receive a notification that their plan is running low on SMS and they should upgrade [reference](https://github.com/ushahidi/RollCall/issues/23)
- [ ]  Owner can modify a monthly SMS plan [Reference](https://github.com/ushahidi/RollCall/issues/23)
